FROM python:3.11-slim

WORKDIR /app

COPY report_pred_api/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY report_pred_api /app/report_pred_api

EXPOSE 8002

CMD ["uvicorn", "report_pred_api.main:app", "--host", "0.0.0.0", "--port", "8002", "--workers", "2"]
